# Generated by Django 3.2.4 on 2021-07-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210705_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('UP', 'Up Vote'), ('Down', 'Down Vote')], max_length=200),
        ),
    ]
